---

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/db_tms?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false'
    username: 'root'
    password: 'mysql'
    driver-class-name: 'com.mysql.jdbc.Driver'

